# 2024.7.4
# >> docker-compose up    << working at docker_flask folder, 2024.7.6
# >> docker-compose -f ./docker_flask/docker-compose.yml up
# >> docker-compose --project-directory ./docker_flask up
# >> docker-compose -p my up
# >> docker-compose -p my up  --build
# >> docker rm -f $(docker ps -aq)        remove all containers
# >> docker rmi -f $(docker images -q)        remove all images
# >> docker exec -it my-server /bin/bash
# ping host.docker.internal in container's shell shows response from 192.168.65.254, 2024.7.7

# 2024.9.1, 'version' is obsolete # version: '3'
# name: my

services:
  flask:
    build:
      context: ..  # directory containing the Dockerfile and other resources needed for building the image
      dockerfile: ./docker_flask/dockerfile
    image: "flask"
    container_name: my-server
    restart: always  # ensure Docker containers to restart automatically after a computer reboot, 2024.7.11
    ports:
      - "8282:5000"  # http://127.0.0.1:8282/  # discarded when using host network mode, 2024.7.8
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://host.docker.internal:27017
        # use 'host.docker.internal' instead of "localhost", 2024.7.8-9
        # network_mode: "host"  # no need to use this to access host network; host.docker.internal is working, 2024.7.9
      - REDIS_URI=redis://redis:6379
      - Y66=${Y66}
    depends_on:
      - redis
  redis:
    image: "redis"
    container_name: redis
    restart: always  # ensure Docker containers to restart automatically after a computer reboot, 2024.7.11
    ports:
      - "6379:6379"