# pipelineflow-low.yml - low-tier deployment definition
deployments:
  - name: pipelineflow-low
    entrypoint: pipeline.py:pipeline       # <file>:<@flow function>
    work_pool:
      name: low_performance
      job_variables:
        image: pipeline-flow:latest
    parameters:
      payload: my_flow.py
