#!/usr/bin/env bash
# __version__ = "0.0.6"  # Semantic Versioning:  Version = Major.Minor.Patch  (bash port of trigger.bat)
#
# trigger_pool.sh — one-shot pool trigger. Calls trigger.sh in --mode pool with everything
# pre-filled, so a single run kicks off the real deployment. Submitter is auto-generated by
# trigger.sh (yRocket-<yyyymmdd-HHMM>-<tz>), so it is not passed here.
#
#   ./trigger_pool.sh
#
# Bump --git-commit after every payload change (the pool runs the pinned SHA, not repo HEAD).
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

"$here/trigger.sh" --mode pool \
  --submitter "" \
  --prefect-block yrocket \
  --prefect-api-url http://192.168.0.13:4200/api \
  --prefect-deployment pipeline/low_deployment \
  --git-repo https://github.com/ykim2718/SandBox4Git.git \
  --git-commit 1e0f8f0280c871d9bc12d7fa08e772bf07db30eb   \
  --minio-key electric_power_consumption/v0/powerconsumption.csv   \
  --payload dry_run/experiment_1/other_flow.py
#  --payload dry_run/my_flow.py

#  1e0f8f0280c871d9bc12d7fa08e772bf07db30eb   >> dry_run/my_flow.py, dry_run/experiment_1/other_flow.py
#   953096e750decf88a47520f336e4269ee1915b6e    << ~8 min
#   0d19d46e2ed3b5144d2a4197b0f77ba969475678    << error
#   95153312753021be0e4c09d04a387d1864de9569    << ~5 sec